version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ai_network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M












  frontend:
    build: ./frontend/my-app
    ports:
      - "3000:80"
    networks:
      - ai_network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

networks:
  ai_network:
