services:
  requirement_gathering_agent:
    build: ./requirement_gathering_agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5001:5001"

  requirements_analysis_agent:
    build: ./requirements_analysis_agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5002:5002"

  sprint_planning_agent:
    build: ./sprint_planning_agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5003:5003"

  approval_agent:
    build: ./approval_agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5004:5004"

  frontend_components_agent:
    build: ./frontend_components_agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5005:5005"

  backend_microservices_agent:
    build: ./backend_microservices_agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5006:5006"

  database_schema_agent:
    build: ./database_schema_agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5007:5007"

  api_gateway_agent:
    build: ./api_gateway_agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5008:5008"

  unit_testing_agent:
    build: ./unit_testing_agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5009:5009"

  deployment_automation_agent:
    build: ./deployment_automation_agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5010:5010"

  logstash:
    build: ./logging
    volumes:
      - ./logging/logstash.conf:/usr/share/logstash/config/logstash.conf
    ports:
      - "5044:5044"
      - "9600:9600"

  kibana:
    build: ./kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"

  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"

  jenkins:
    build: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
