global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['jenkins:8080']
      
  - job_name: 'logstash'
    metrics_path: '/_prometheus/metrics'
    static_configs:
      - targets: ['logstash:9600']
      
  - job_name: 'kibana'
    metrics_path: '/_prometheus/metrics'
    static_configs:
      - targets: ['kibana:5601']
